export const causes = [
  {
    id: 1,
    title: "Clean Water for All",
    image: "/assets/c1.jpg",
    description: "Lorem donec eget morbi nisi. Eu ut et enim ornare nisl vel auctor odio.",
    goal: 12000,
    raised: 8000,
    donations: 14,
  },
  {
    id: 2,
    title: "Improve Education",
    image: "/assets/c2.jpg",
    description: "Lorem donec eget morbi nisi. Eu ut et enim ornare nisl vel auctor odio.",
    goal: 15000,
    raised: 12000,
    donations: 25,
  },
  {
    id: 3,
    title: "End Hunger",
    image: "/assets/c3.jpg",
    description: "Lorem donec eget morbi nisi. Eu ut et enim ornare nisl vel auctor odio.",
    goal: 20000,
    raised: 8000,
    donations: 6,
  },
  {
    id: 4,
    title: "Reduce Homelessness",
    image: "/assets/c1.jpg",
    description: "Lorem donec eget morbi nisi.",
    goal: 60000,
    raised: 32000,
    donations: 12,
  },
  {
    id: 5,
    title: "Immigration and Refugees",
    image: "/assets/c2.jpg",
    description: "Lorem donec eget morbi nisi.",
    goal: 22000,
    raised: 6000,
    donations: 24,
  },
  {
    id: 6,
    title: "Climate Change Mitigation",
    image: "/assets/c3.jpg",
    description: "Lorem donec eget morbi nisi.",
    goal: 12000,
    raised: 8000,
    donations: 8,
  },
];